---
title: "SFB Rmd"
output: github_document
---
```{r}
# library(ffsimulator)
pkgload::load_all()
library(ffscrapr)
library(tidyverse)
library(furrr)

plan(multisession)
```


```{r import_data}
conn <- mfl_connect(2021, 47747)

league_info <- ffscrapr::ff_league(conn)

scoring_history <- ffscrapr::ff_scoringhistory(conn, 2012:2020)

tictoc::tic()
adp_outcomes <- ffs_adp_outcomes(scoring_history = scoring_history, injury_model = "simple")
tictoc::toc()

tictoc::tic()
latest_rankings <- ffs_latest_rankings()
tictoc::toc()

lineup_constraints <- ffscrapr::ff_starter_positions(conn)

```


```{r sfb_rosters}
conn2 <- mfl_connect(2021)

leagues <- mfl_getendpoint(conn2, "leagueSearch", SEARCH = "#SFB11") %>%
  pluck("content","leagues","league") %>%
  tibble() %>%
  unnest_wider(1) %>%
  filter(str_detect(name,"Mock|Copy|Satellite|Template",negate = TRUE))


get_rosters <- function(league_id){
  mfl_connect(2021, league_id, user_agent = glue::glue("dynastyprocess/{league_id}"), rate_limit = FALSE) %>%
    ffs_rosters()
}
get_franchises <- function(league_id){
  mfl_connect(2021, league_id, user_agent = glue::glue("dynastyprocess/{league_id}"), rate_limit = FALSE) %>%
    ff_franchises()
}

rosters_raw <- leagues %>%
  select(-homeURL) %>%
  mutate(
    rosters = future_map(id, get_rosters),
    franchises = future_map(id, get_franchises)
  )

franchises <- rosters_raw %>%
  select(league_id = id, franchises) %>%
  unnest(franchises) %>%
  select(league_id, franchise_id, division_name)

rosters <- rosters_raw %>%
  select(rosters) %>%
  unnest(rosters) %>%
  left_join(franchises,by = c("league_id","franchise_id"))
```


```{r generate_projections}
n_seasons <- 100
n_weeks <- 13
tictoc::tic()
projected_scores <- ffs_generate_projections(adp_outcomes = adp_outcomes,
                                             latest_rankings = latest_rankings,
                                             n_seasons = n_seasons,
                                             n_weeks = n_weeks,
                                             rosters = rosters)
tictoc::toc()
```


```{r join_projections_to_rosters}
tictoc::tic()
roster_scores <- ffs_score_rosters(projected_scores, rosters)
tictoc::toc()
```


```{r optimize_lineups}
tictoc::tic()
optimal_scores <- ffs_optimize_lineups(
  roster_scores = roster_scores,
  lineup_constraints = lineup_constraints,
  best_ball = FALSE,
  parallel = TRUE)
tictoc::toc()
```


```{r schedule_and_summarise}
tictoc::tic()
schedules <- ffs_build_schedules(n_teams = rosters %>%
                                   dplyr::distinct(.data$league_id,.data$franchise_id) %>%
                                   nrow(),
                                 n_seasons = n_seasons,
                                 n_weeks = n_weeks)
tictoc::toc()
tictoc::tic()
summary_week <- ffs_summarise_week(optimal_scores, schedules)
tictoc::toc()
tictoc::tic()
summary_season <- ffs_summarise_season(summary_week)
tictoc::toc()
tictoc::tic()
summary_simulation <- ffs_summarise_simulation(summary_season)
tictoc::toc()

```

