#' Optimize Lineups
#'
#' Optimizes lineups for all franchises in the dataframe based on a table of lineup constraints
#'
#' @param projected_scores a dataframe as generated by `ffs_generate_predictions()` - should contain columns like: projected_score, pos, and player_id
#' @param lineup_constraints a dataframe as generated by `ffscrapr::ff_starter_positions()` - should contain columns pos, min, max, and offense_starters
#' @param best_ball a logical: FALSE will apply a lineup efficiency factor and TRUE uses optimal scores as actual scores, default = FALSE
#' @param parallel a logical: TRUE will run the optimization in parallel, requires the furrr and future packages as well as setting `future::plan()` in advance/externally. Default FALSE.
#'
#' @export
ffs_optimize_lineups <- function(projected_scores,
                                 lineup_constraints,
                                 best_ball = FALSE,
                                 parallel = FALSE){

  stopifnot(is.logical(parallel))
  stopifnot(is.logical(best_ball))

  if(!parallel) map <- purrr::map

  if(parallel && suppressMessages(requireNamespace("furrr"))) {
    map <- furrr::future_map

    if(inherits(future::plan(), "sequential")) {
      message("Parallel processing was specified but no future::plan() was found. Continuing sequentially.")
    }
  }

  nest_data <- projected_scores %>%
    dplyr::left_join(
      lineup_constraints %>% dplyr::select("pos", "max"),
      by = "pos") %>%
    dplyr::filter(.data$pos_rank <= .data$max, pos %in% c("QB","RB","WR","TE")) %>%
    dplyr::group_by(.data$franchise_id, .data$franchise_name, .data$n) %>%
    tidyr::nest() %>%
    dplyr::ungroup()

  if(best_ball) lineup_efficiency <- 1

  if(!best_ball) lineup_efficiency <- stats::rnorm(nrow(nest_data), mean = 0.775, sd = 0.05)

  optimal_scores <- nest_data %>%
    dplyr::mutate(
      optimals = map(.data$data, ffsimulator::.ff_optimize_one_lineup, lineup_constraints),
      data = NULL
    ) %>%
    tidyr::unnest_wider("optimals") %>%
    dplyr::bind_cols(lineup_efficiency = lineup_efficiency) %>%
    dplyr::mutate(actual_score = .data$optimal_score * .data$lineup_efficiency)

  return(optimal_scores)
}

#' Optimize single lineup
#'
#' Optimizes lineups for one franchise week at a time. Use purrr or loop to do more franchises/weeks/seasons
#'
#' @param franchise_scores a data frame of scores for one week and one franchise
#' @param lineup_constraints a data frame as created by `ffscrapr::ff_starter_positions()`
#'
#' @return a list including the optimal_score and the optimal_lineup tibble.
#'
#' @export
.ff_optimize_one_lineup <- function(franchise_scores, lineup_constraints){

  score_obj <- tidyr::replace_na(franchise_scores$projected_score,0)

  # binary - position identifiers

  pos_ids <- NULL

  for(i in lineup_constraints$pos) pos_ids <- c(pos_ids, as.integer(franchise_scores$pos == i))

  constraints_matrix <- matrix(
    c(pos_ids, #pos minimums
      pos_ids, #pos maximums
      as.integer(franchise_scores$pos %in% c("QB","RB","WR","TE"))), # total offensive starters
    nrow = nrow(lineup_constraints)*2 + 1,
    byrow = TRUE
  )

  constraints_dir <- c(rep_len(">=", nrow(lineup_constraints)),
                       rep_len("<=", nrow(lineup_constraints)),
                       "<=")

  constraints_rhs <- c(lineup_constraints$min,
                       lineup_constraints$max,
                       lineup_constraints$offense_starters[[1]])

  solve_lineup <- Rglpk::Rglpk_solve_LP(
    obj = score_obj,
    mat = constraints_matrix,
    dir = constraints_dir,
    rhs = constraints_rhs,
    types = rep("B", length(score_obj)),
    max = TRUE
  )

  optimals <- list(
    optimal_score = sum(franchise_scores$projected_score * solve_lineup$solution),
    optimal_lineup = data.frame(
      player_id = franchise_scores$player_id[as.logical(solve_lineup$solution)],
      player_score = franchise_scores$projected_score[as.logical(solve_lineup$solution)]
    ))

  return(optimals)
}

#' @export
#' @rdname ffs_optimize_lineups
ffs_optimise_lineups <- ffs_optimize_lineups
